#!/usr/bin/env bash

# Read API key from ~/.btc/coinbase_api_key

api_key_file=$HOME/.btc/coinbase_api_key
spot_rate_api="https://coinbase.com/api/v1/prices/spot_rate?api_key="
buy_rate_api="https://coinbase.com/api/v1/prices/buy?api_key="
sell_rate_api="https://coinbase.com/api/v1/prices/sell?api_key="

if [ -e $api_key_file ]; then
  echo "Reading config file..."
  source $api_key_file
else
  echo "The $api_key_file file does not exist"
  exit 1
fi

case "$1" in
  'buy')
    json=`curl -s -X GET ${buy_rate_api}${api_key}`
    buy_rate=`echo $json | jq .amount | tr -d '"'`
    currency=`echo $json | jq .currency | tr -d '"'`
    echo "$buy_rate $currency"
    ;;
  'sell')
    json=`curl -s -X GET ${sell_rate_api}${api_key}`
    sell_rate=`echo $json | jq .amount | tr -d '"'`
    currency=`echo $json | jq .currency | tr -d '"'`
    echo "$sell_rate $currency"
    ;;
  *)
    json=`curl -s -X GET ${spot_rate_api}${api_key}`
    spot_rate=`echo $json | jq .amount | tr -d '"'`
    currency=`echo $json | jq .currency | tr -d '"'`
    echo "$spot_rate $currency"
    ;;
esac

exit 0
